services:
  application:
    build: ./
    image: ${CI_REGISTRY_IMAGE:-grug}:latest
    restart: unless-stopped
    env_file:
      - config/postgres.env
      - ${SECRETS_ENV_FILE:-config/secrets.env}

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./config/postgres.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  postgres_data:
