services:
  application:
    build: ./
    image: ${CI_REGISTRY_IMAGE:-grug}:latest
    restart: unless-stopped
    env_file:
      - path: config/postgres.env
        required: true
      - path: ${SECRETS_ENV_FILE:-config/secrets.env}
        required: true
    ports:
      - "9089:9000"

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - path: ./config/postgres.env
        required: true
    ports:
      - "5432:5432"

volumes:
  postgres_data:
