[tool.poetry]
name = "grug"
version = "1.0.0"
description = ""
authors = ["Foehammer82 <contact-project+dark-water-grug-57605831-issue-@incoming.gitlab.com>"]
readme = "README.md"
packages = [{ include = "grug" }]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"
sqlmodel = "^0.0"
discord-py = { extras = ["voice"], version = "^2.3" }
alembic = "^1.13"
pydantic = "^2.7"
pydantic-settings = "^2.4"
email-validator = "^2.1"
apscheduler = { version = "<5", allow-prereleases = true }
croniter = "^3.0"
openai = "^1.30"
loguru = "^0.7"
elasticsearch = "^8.13"
python-jose = {extras = ["cryptography"], version = "^3.3"}
alembic-postgresql-enum = "^1.2"
sentry-sdk = {extras = ["loguru"], version = "^2.5"}
psycopg = {extras = ["binary", "pool"], version = "^3.2"}
asyncpg = "^0.29.0"
anyio = "^4.4"

[tool.poetry.group.test.dependencies]
pytest = "^8.1"
pytest-asyncio = "^0.23"
pytest-cov = "^5.0"
faker = "^25.2"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6"
black = "^24.2"
jupyter = "^1.0.0"

[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
extend-exclude = '''
/(
  | alembic/versions
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
asyncio_mode = "auto"
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.interrogate]
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = false
ignore-setters = false
ignore-overloaded-functions = false
fail-under = 100
exclude = ["setup.py", "docs", "build", "alembic", "tests"]
ext = []
style = "google"
verbose = 1
quiet = false
whitelist-regex = []
color = true
omit-covered-files = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101", "B601", "B301", "B403", "B608"]
