"""init

Revision ID: 0b2cc423c3cc
Revises: 
Create Date: 2023-01-06 13:08:03.296172

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0b2cc423c3cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_guild_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_guild_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brings_food', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dndsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_guild_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('food_bringer_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_bringer_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foodselectionmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dnd_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dnd_session_id'], ['dndsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodselectionmessage_discord_message_id'), 'foodselectionmessage', ['discord_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foodselectionmessage_discord_message_id'), table_name='foodselectionmessage')
    op.drop_table('foodselectionmessage')
    op.drop_table('dndsession')
    op.drop_table('player')
    # ### end Alembic commands ###
