"""auto

Revision ID: fb0301ba2bd8
Revises: 20260304_0000_grug_notes
Create Date: 2026-03-04 00:40:44.548745
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb0301ba2bd8"
down_revision: Union[str, None] = "20260304_0000_grug_notes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_documents_guild_content_hash"),
        table_name="documents",
        postgresql_where="(content_hash IS NOT NULL)",
    )
    op.alter_column(
        "grug_notes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "grug_notes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        "fk_user_active_character",
        "user_profiles",
        "characters",
        ["active_character_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_active_character", "user_profiles", type_="foreignkey")
    op.alter_column(
        "grug_notes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "grug_notes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("uq_documents_guild_content_hash"),
        "documents",
        ["guild_id", "content_hash"],
        unique=True,
        postgresql_where="(content_hash IS NOT NULL)",
    )
    # ### end Alembic commands ###
