"""rename discordtextchannels

Revision ID: 29bd138608df
Revises: e774abf536ff
Create Date: 2024-09-18 11:16:25.931603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '29bd138608df'
down_revision = 'e774abf536ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_text_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('assistant_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discord_text_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_text_channels_discord_channel_id'), ['discord_channel_id'], unique=False)

    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.drop_index('ix_discordtextchannel_discord_channel_id')

    op.drop_table('discordtextchannel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discordtextchannel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('discord_channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('assistant_thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='discordtextchannel_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discordtextchannel_pkey')
    )
    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.create_index('ix_discordtextchannel_discord_channel_id', ['discord_channel_id'], unique=False)

    with op.batch_alter_table('discord_text_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_text_channels_discord_channel_id'))

    op.drop_table('discord_text_channels')
    # ### end Alembic commands ###
