"""fix nullable group id

Revision ID: 2ef853337bf0
Revises: 661bc1ebdbac
Create Date: 2024-10-27 19:23:44.608287

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2ef853337bf0'
down_revision = '661bc1ebdbac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
