"""cleanup relations

Revision ID: 320c5a4f6d89
Revises: 63260dbcbab1
Create Date: 2024-06-06 10:29:19.040018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '320c5a4f6d89'
down_revision = '63260dbcbab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
