"""cleanup unused relationships

Revision ID: 367bbe5abf39
Revises: 2ef853337bf0
Create Date: 2024-10-27 19:32:27.358419

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '367bbe5abf39'
down_revision = '2ef853337bf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_text_channels', schema=None) as batch_op:
        batch_op.drop_constraint('discord_text_channels_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_text_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('discord_text_channels_group_id_fkey', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
