"""add compound unique index to event sub models

Revision ID: 63260dbcbab1
Revises: 709dd696a71c
Create Date: 2024-06-05 12:44:15.532750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '63260dbcbab1'
down_revision = '709dd696a71c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        # batch_op.drop_index('compound_index_event_id_event_date')
        batch_op.create_index('compound_index_event_attendance_event_id_date', ['event_id', 'event_date'], unique=True)

    with op.batch_alter_table('event_food', schema=None) as batch_op:
        batch_op.create_index('compound_index_event_food_event_id_date', ['event_id', 'event_date'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_food', schema=None) as batch_op:
        batch_op.drop_index('compound_index_event_food_event_id_date')

    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.drop_index('compound_index_event_attendance_event_id_date')
        batch_op.create_index('compound_index_event_id_event_date', ['event_id', 'event_date'], unique=True)

    # ### end Alembic commands ###
