"""add discord channel

Revision ID: 6c59b9b93492
Revises: c21321e358e3
Create Date: 2023-01-16 21:54:40.679392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6c59b9b93492'
down_revision = 'c21321e358e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dndsession', sa.Column('discord_main_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dndsession', 'discord_main_channel_id')
    # ### end Alembic commands ###
