"""remove discord channel selection from session

Revision ID: 6f32a48327f0
Revises: 6c59b9b93492
Create Date: 2023-02-06 00:52:58.878979

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6f32a48327f0'
down_revision = '6c59b9b93492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dndsession', schema=None) as batch_op:
        batch_op.drop_column('discord_main_channel_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dndsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_main_channel_id', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
