"""add food_reminder_time

Revision ID: 700cc7229e1f
Revises: a656de6af92b
Create Date: 2024-06-02 20:23:35.359939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '700cc7229e1f'
down_revision = 'a656de6af92b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_schedule_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_schedule_minute', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('food_reminder_time_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('food_reminder_time_minute', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attendance_reminder_time_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attendance_reminder_time_minute', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('attendance_reminder_time_minute')
        batch_op.drop_column('attendance_reminder_time_hour')
        batch_op.drop_column('food_reminder_time_minute')
        batch_op.drop_column('food_reminder_time_hour')
        batch_op.drop_column('event_schedule_minute')
        batch_op.drop_column('event_schedule_hour')

    # ### end Alembic commands ###
