"""add bot channel to discord server

Revision ID: 709dd696a71c
Revises: aa50151fba6c
Create Date: 2024-06-05 11:00:18.680901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '709dd696a71c'
down_revision = 'aa50151fba6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_bot_channel_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_servers', schema=None) as batch_op:
        batch_op.drop_column('discord_bot_channel_id')

    # ### end Alembic commands ###
