"""new scheduling trigger system

Revision ID: 814943596756
Revises: 700cc7229e1f
Create Date: 2024-06-02 20:49:03.782008

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '814943596756'
down_revision = '700cc7229e1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_schedule_start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('food_reminder_days_before_event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attendance_reminder_days_before_event',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('food_reminder_cron')
        batch_op.drop_column('attendance_reminder_cron')
        batch_op.drop_column('event_schedule_cron')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_schedule_cron', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attendance_reminder_cron', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_reminder_cron', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('attendance_reminder_days_before_event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('food_reminder_days_before_event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_schedule_start_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
