"""add discord text channel

Revision ID: 9d37c464ee02
Revises: 1935af011a6d
Create Date: 2024-03-12 09:58:43.273260

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9d37c464ee02'
down_revision = '1935af011a6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discordtextchannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('assistant_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discordtextchannel_discord_id'), ['discord_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discordtextchannel_discord_id'))

    op.drop_table('discordtextchannel')
    # ### end Alembic commands ###
