"""switch discord id from int to str

Revision ID: adb39a613acd
Revises: 904c05ff7576
Create Date: 2024-03-12 10:55:39.451311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'adb39a613acd'
down_revision = '904c05ff7576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.alter_column('discord_id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discordtextchannel', schema=None) as batch_op:
        batch_op.alter_column('discord_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
