"""test-2

Revision ID: b83544a08082
Revises: 814943596756
Create Date: 2024-06-02 21:03:15.432127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b83544a08082'
down_revision = '814943596756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_schedule_start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('attendance_reminder_time', sa.Time(), nullable=False))
        batch_op.drop_column('event_schedule_hour')
        batch_op.drop_column('event_schedule_start_date')
        batch_op.drop_column('event_schedule_minute')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_schedule_minute', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_schedule_start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_schedule_hour', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('attendance_reminder_time')
        batch_op.drop_column('event_schedule_start_datetime')

    # ### end Alembic commands ###
