"""add timedelta to event

Revision ID: d1948af1e76a
Revises: 9045c878d9c4
Create Date: 2024-05-13 23:14:43.041826

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd1948af1e76a'
down_revision = '9045c878d9c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
