"""discord interaction audit

Revision ID: e774abf536ff
Revises: d9eab80a6580
Create Date: 2024-09-18 11:15:00.545151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e774abf536ff'
down_revision = 'd9eab80a6580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_interaction_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.BigInteger(), nullable=True),
    sa.Column('interaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('interaction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discord_interaction_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_interaction_audits_interaction_id'), ['interaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord_interaction_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_interaction_audits_interaction_id'))

    op.drop_table('discord_interaction_audits')
    # ### end Alembic commands ###
