"""add dalle tracking

Revision ID: f3680e87f410
Revises: 320c5a4f6d89
Create Date: 2024-06-09 20:31:30.320346

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f3680e87f410'
down_revision = '320c5a4f6d89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dalle_image_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revised_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dalle_image_requests')
    # ### end Alembic commands ###
