"""adjust rsvp models

Revision ID: f66843e1a0e8
Revises: 340462ee64d5
Create Date: 2024-06-20 16:31:09.205462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f66843e1a0e8'
down_revision = '340462ee64d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_occurrence_rsvp_no_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_attendance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_attendance_id'], ['event_occurrence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_attendance_id')
    )
    op.create_table('user_event_occurrence_rsvp_yes_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_attendance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_attendance_id'], ['event_occurrence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_attendance_id')
    )
    op.drop_table('users_events_attendance_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_events_attendance_link',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_attendance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_attendance_id'], ['event_occurrence.id'], name='users_events_attendance_link_event_attendance_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_events_attendance_link_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'event_attendance_id', name='users_events_attendance_link_pkey')
    )
    op.drop_table('user_event_occurrence_rsvp_yes_link')
    op.drop_table('user_event_occurrence_rsvp_no_link')
    # ### end Alembic commands ###
